# Generated by Django 6.1 on 2026-08-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bound_device_id",
            field=models.CharField(
                blank=True,
                help_text="معرّف الجهاز المرتبط بحساب موظف الدخول — يُضبط تلقائيًا أول استخدام",
                max_length=255,
                null=True,
            ),
        ),
    ]
