# Generated by Django 6.1 on 2026-08-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_bound_device_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bound_device_id",
        ),
        migrations.AddField(
            model_name="user",
            name="device_id",
            field=models.CharField(
                blank=True,
                help_text="معرّف الجهاز المرتبط بالحساب — يُضبط تلقائيًا أول استخدام",
                max_length=255,
                null=True,
            ),
        ),
    ]
