# Generated by Django 6.1 on 2026-08-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_user_bound_device_id_user_device_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_first_login",
            field=models.BooleanField(
                default=True, help_text="يصبح False بعد أول تغيير لكلمة المرور"
            ),
        ),
    ]
