# Generated by Django 6.1 on 2026-08-17 08:47

from django.db import migrations, models
from django.db.models import Count


def dedupe_phone_numbers(apps, schema_editor):
    """يفرغ رقم الهاتف الفارغ (لتفادي تعارض التفرّد) ويُبقي الرقم عند أقدم حساب فقط عند التكرار."""
    User = apps.get_model("accounts", "User")
    User.objects.filter(phone="").update(phone=None)

    duplicates = (
        User.objects.exclude(phone__isnull=True)
        .exclude(phone="")
        .values("phone")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )
    for entry in duplicates:
        ids_to_clear = list(
            User.objects.filter(phone=entry["phone"]).order_by("id").values_list("id", flat=True)[1:]
        )
        User.objects.filter(id__in=ids_to_clear).update(phone=None)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_phone"),
    ]

    operations = [
        migrations.RunPython(dedupe_phone_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
