# Generated by Django 6.1 on 2026-08-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_phone_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.PositiveIntegerField(
                blank=True, help_text="تصنيف الموظف داخل الشركة", null=True
            ),
        ),
    ]
