# Generated by Django 6.1 on 2026-08-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_regular",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                blank=True, help_text="نوع الدوام", max_length=50, null=True
            ),
        ),
    ]
