# Generated by Django 6.1 on 2026-08-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_user_type_to_char"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="entity",
            field=models.CharField(
                blank=True,
                help_text="الجهة التي يتبع لها الموظف",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tc",
            field=models.CharField(
                blank=True,
                help_text="الرقم الوطني (TC)",
                max_length=11,
                null=True,
                unique=True,
            ),
        ),
    ]
