# Generated by Django 6.1 on 2026-08-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qr_token_lifetime_seconds",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="مدة صلاحية رمز QR بالثواني — نفس المدة تُستخدم كفاصل التحديث التلقائي في شاشة الدخول",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
    ]
