# Generated by Django 6.1 on 2026-08-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_systemsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qrtoken",
            name="action",
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="min_session_duration_seconds",
            field=models.PositiveIntegerField(
                default=60,
                help_text="أقل مدة مسموحة بين تسجيل الدخول والخروج لنفس الجلسة — يمنع تسجيل خروج فوري بعد الدخول مباشرة",
            ),
        ),
    ]
