# Generated by Django 6.1 on 2026-08-13 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_qrtoken_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="work_start_time",
            field=models.TimeField(
                default=datetime.time(9, 0),
                help_text="وقت بدء الدوام الرسمي — يُستخدم لحساب دقائق التأخير في التقارير",
            ),
        ),
    ]
