# Generated by Django 6.1 on 2026-08-14 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_systemsettings_work_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="work_end_time",
            field=models.TimeField(
                default=datetime.time(17, 0),
                help_text="وقت انتهاء الدوام الرسمي — يُستخدم لحساب دقائق الانصراف المبكر في التقارير",
            ),
        ),
    ]
