# Generated by Django 6.1 on 2026-08-14 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_attendance_id_alter_qrtoken_id_and_more"),
        ("core", "0005_systemsettings_work_end_time"),
    ]

    operations = []
