# Generated by Django 6.1 on 2026-08-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_merge_20260814_1112"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemsettings",
            name="min_session_duration_seconds",
            field=models.PositiveIntegerField(
                default=60,
                help_text=(
                    "أقل مدة مسموحة بين تسجيل الدخول والخروج لنفس الجلسة، وأيضًا بين الخروج وتسجيل دخول جديد بعده — "
                    "يمنع تسجيل خروج فوري بعد الدخول، أو دخول فوري بعد الخروج، بالغلط"
                ),
            ),
        ),
    ]
