# Generated by Django 6.1 on 2026-08-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_min_session_duration_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='block_irregular_employees',
            field=models.BooleanField(default=True, help_text='لما تكون مفعّلة، الموظفون غير النظاميين (is_regular=False) ما يقدرون يسجّلون دخول إطلاقًا، وأي جلسة مفتوحة عندهم حاليًا تُرفض بأول طلب جاي منهم — بنفس رسالة خطأ اسم المستخدم/كلمة المرور الخاطئة، حتى ما يعرفوا إنه تم حظرهم تحديدًا.'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qrtoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
